version: '3.8'

services:
  app:
    container_name: cicd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - test
    restart: unless-stopped
networks:
  test:
    driver: bridge