version: '3.8'

services:
  app:
    container_name: cicd
    image: amerkul/cicd:latest
    ports:
      - "8888:8888"
    networks:
      - test
    restart: unless-stopped
networks:
  test:
    driver: bridge
