name: CI Workflow with Maven

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push-to-registry:

    runs-on: ubuntu-latest

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build jar with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: amerkul/cicd
          tags: 1.0.$GITHUB_RUN_NUMBER, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull & Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ${{ secrets.TEST_EC2_USERNAME }}
          key: ${{ secrets.TEST_EC2_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 
            docker stop amerkul/cicd || true
            docker rm amerkul/cicd || true
            docker pull amerkul/cicd:1.0.${{ GITHUB_RUN_NUMBER }}
            docker run -d -p 8888:8888 amerkul/cicd:1.0.${{ GITHUB_RUN_NUMBER }}
